<?php

namespace Modules\Tenants\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

/**
 * Comprehensive Archdioceses Seeder
 * 
 * Seeds the archdioceses table with Catholic dioceses and archdioceses 
 * from major Christian countries worldwide.
 * 
 * Data sources:
 * - https://en.wikipedia.org/wiki/List_of_Catholic_dioceses
 * - https://www.catholic-hierarchy.org
 * - https://www.gcatholic.org
 * 
 * Countries covered:
 * - India, United States, Brazil, Philippines, Italy, France, Spain
 * - Germany, Nigeria, Mexico, Poland, Canada, Argentina, Kenya
 * - Australia, United Kingdom
 */
class ArchdiocesesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get denomination IDs
        $catholicId = DB::table('denominations')->where('code', 'CATHOLIC')->value('id');
        $anglicanId = DB::table('denominations')->where('code', 'ANGLICAN')->value('id');

        $archdioceses = [
            // ================================================================
            // INDIA - Catholic Dioceses and Archdioceses
            // ================================================================
            [
                'name' => 'Archdiocese of Bangalore',
                'code' => 'BANGALORE',
                'country' => 'India',
                'region' => 'Karnataka',
                'headquarters_city' => 'Bangalore',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Metropolitan archdiocese in South India',
                'website' => 'https://www.bangalorearchdiocese.com',
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Mumbai (Bombay)',
                'code' => 'MUMBAI',
                'country' => 'India',
                'region' => 'Maharashtra',
                'headquarters_city' => 'Mumbai',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major metropolitan archdiocese in Western India',
                'website' => 'https://www.bombaycatholicarchdiocese.com',
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Goa and Daman',
                'code' => 'GOA',
                'country' => 'India',
                'region' => 'Goa',
                'headquarters_city' => 'Panaji',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Historic archdiocese, oldest in India',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Delhi',
                'code' => 'DELHI',
                'country' => 'India',
                'region' => 'Delhi',
                'headquarters_city' => 'New Delhi',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Archdiocese serving the national capital',
                'website' => 'https://www.archdioceseofdelhi.org',
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Madras and Mylapore',
                'code' => 'MADRAS_MYLAPORE',
                'country' => 'India',
                'region' => 'Tamil Nadu',
                'headquarters_city' => 'Chennai',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Metropolitan archdiocese in Tamil Nadu',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Calcutta (Kolkata)',
                'code' => 'CALCUTTA',
                'country' => 'India',
                'region' => 'West Bengal',
                'headquarters_city' => 'Kolkata',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Metropolitan archdiocese in Eastern India',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Hyderabad',
                'code' => 'HYDERABAD',
                'country' => 'India',
                'region' => 'Telangana',
                'headquarters_city' => 'Hyderabad',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Archdiocese in Central India',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Nagpur',
                'code' => 'NAGPUR',
                'country' => 'India',
                'region' => 'Maharashtra',
                'headquarters_city' => 'Nagpur',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Archdiocese in Central India',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Ranchi',
                'code' => 'RANCHI',
                'country' => 'India',
                'region' => 'Jharkhand',
                'headquarters_city' => 'Ranchi',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese in tribal regions',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Shillong',
                'code' => 'SHILLONG',
                'country' => 'India',
                'region' => 'Meghalaya',
                'headquarters_city' => 'Shillong',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Metropolitan archdiocese in Northeast India',
                'website' => null,
                'active' => 1,
            ],

            // ================================================================
            // UNITED STATES - Catholic Dioceses and Archdioceses
            // ================================================================
            [
                'name' => 'Archdiocese of New York',
                'code' => 'NEW_YORK',
                'country' => 'United States',
                'region' => 'New York',
                'headquarters_city' => 'New York City',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'One of the largest archdioceses in the US',
                'website' => 'https://archny.org',
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Los Angeles',
                'code' => 'LOS_ANGELES',
                'country' => 'United States',
                'region' => 'California',
                'headquarters_city' => 'Los Angeles',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Largest Catholic archdiocese in the US',
                'website' => 'https://lacatholics.org',
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Chicago',
                'code' => 'CHICAGO',
                'country' => 'United States',
                'region' => 'Illinois',
                'headquarters_city' => 'Chicago',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese in the Midwest',
                'website' => 'https://archchicago.org',
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Washington',
                'code' => 'WASHINGTON_DC',
                'country' => 'United States',
                'region' => 'District of Columbia',
                'headquarters_city' => 'Washington',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Archdiocese of the nation\'s capital',
                'website' => 'https://adw.org',
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Boston',
                'code' => 'BOSTON',
                'country' => 'United States',
                'region' => 'Massachusetts',
                'headquarters_city' => 'Boston',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Historic archdiocese in New England',
                'website' => 'https://www.bostoncatholic.org',
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Philadelphia',
                'code' => 'PHILADELPHIA',
                'country' => 'United States',
                'region' => 'Pennsylvania',
                'headquarters_city' => 'Philadelphia',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major East Coast archdiocese',
                'website' => 'https://archphila.org',
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Detroit',
                'code' => 'DETROIT',
                'country' => 'United States',
                'region' => 'Michigan',
                'headquarters_city' => 'Detroit',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese in the Great Lakes region',
                'website' => 'https://aod.org',
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Miami',
                'code' => 'MIAMI',
                'country' => 'United States',
                'region' => 'Florida',
                'headquarters_city' => 'Miami',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese in South Florida',
                'website' => 'https://www.miamiarch.org',
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of San Francisco',
                'code' => 'SAN_FRANCISCO',
                'country' => 'United States',
                'region' => 'California',
                'headquarters_city' => 'San Francisco',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Historic West Coast archdiocese',
                'website' => 'https://sfarch.org',
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Seattle',
                'code' => 'SEATTLE',
                'country' => 'United States',
                'region' => 'Washington',
                'headquarters_city' => 'Seattle',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Pacific Northwest archdiocese',
                'website' => 'https://seattlearch.org',
                'active' => 1,
            ],

            // ================================================================
            // BRAZIL - Catholic Dioceses and Archdioceses
            // ================================================================
            [
                'name' => 'Archdiocese of São Paulo',
                'code' => 'SAO_PAULO',
                'country' => 'Brazil',
                'region' => 'São Paulo',
                'headquarters_city' => 'São Paulo',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Largest archdiocese in Brazil',
                'website' => 'https://www.arquisp.org.br',
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Rio de Janeiro',
                'code' => 'RIO_DE_JANEIRO',
                'country' => 'Brazil',
                'region' => 'Rio de Janeiro',
                'headquarters_city' => 'Rio de Janeiro',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Historic archdiocese in Rio',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Brasília',
                'code' => 'BRASILIA',
                'country' => 'Brazil',
                'region' => 'Federal District',
                'headquarters_city' => 'Brasília',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Archdiocese of the capital',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Belo Horizonte',
                'code' => 'BELO_HORIZONTE',
                'country' => 'Brazil',
                'region' => 'Minas Gerais',
                'headquarters_city' => 'Belo Horizonte',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese in Southeast Brazil',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Salvador da Bahia',
                'code' => 'SALVADOR',
                'country' => 'Brazil',
                'region' => 'Bahia',
                'headquarters_city' => 'Salvador',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Primate archdiocese of Brazil',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Fortaleza',
                'code' => 'FORTALEZA',
                'country' => 'Brazil',
                'region' => 'Ceará',
                'headquarters_city' => 'Fortaleza',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Northeast Brazil archdiocese',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Curitiba',
                'code' => 'CURITIBA',
                'country' => 'Brazil',
                'region' => 'Paraná',
                'headquarters_city' => 'Curitiba',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese in South Brazil',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Porto Alegre',
                'code' => 'PORTO_ALEGRE',
                'country' => 'Brazil',
                'region' => 'Rio Grande do Sul',
                'headquarters_city' => 'Porto Alegre',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Southernmost major archdiocese',
                'website' => null,
                'active' => 1,
            ],

            // ================================================================
            // PHILIPPINES - Catholic Dioceses and Archdioceses
            // ================================================================
            [
                'name' => 'Archdiocese of Manila',
                'code' => 'MANILA',
                'country' => 'Philippines',
                'region' => 'Metro Manila',
                'headquarters_city' => 'Manila',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Oldest and most prominent archdiocese in the Philippines',
                'website' => 'https://www.rcam.org',
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Cebu',
                'code' => 'CEBU',
                'country' => 'Philippines',
                'region' => 'Central Visayas',
                'headquarters_city' => 'Cebu City',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Oldest archdiocese in the Philippines',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Davao',
                'code' => 'DAVAO',
                'country' => 'Philippines',
                'region' => 'Davao Region',
                'headquarters_city' => 'Davao City',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese in Mindanao',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Cotabato',
                'code' => 'COTABATO',
                'country' => 'Philippines',
                'region' => 'Soccsksargen',
                'headquarters_city' => 'Cotabato City',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Archdiocese in Central Mindanao',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Lingayen-Dagupan',
                'code' => 'LINGAYEN_DAGUPAN',
                'country' => 'Philippines',
                'region' => 'Ilocos Region',
                'headquarters_city' => 'Dagupan',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese in Luzon',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Cagayan de Oro',
                'code' => 'CAGAYAN_DE_ORO',
                'country' => 'Philippines',
                'region' => 'Northern Mindanao',
                'headquarters_city' => 'Cagayan de Oro',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Archdiocese in Northern Mindanao',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Jaro',
                'code' => 'JARO',
                'country' => 'Philippines',
                'region' => 'Western Visayas',
                'headquarters_city' => 'Iloilo City',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Historic archdiocese in the Visayas',
                'website' => null,
                'active' => 1,
            ],

            // ================================================================
            // ITALY - Catholic Dioceses and Archdioceses
            // ================================================================
            [
                'name' => 'Archdiocese of Rome (Vatican)',
                'code' => 'ROME',
                'country' => 'Vatican City',
                'region' => 'Lazio',
                'headquarters_city' => 'Vatican City',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'The Diocese of Rome, seat of the Pope',
                'website' => 'https://www.diocesidiroma.it',
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Milan',
                'code' => 'MILAN',
                'country' => 'Italy',
                'region' => 'Lombardy',
                'headquarters_city' => 'Milan',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Largest archdiocese in Europe',
                'website' => 'https://www.chiesadimilano.it',
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Naples',
                'code' => 'NAPLES',
                'country' => 'Italy',
                'region' => 'Campania',
                'headquarters_city' => 'Naples',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese in Southern Italy',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Florence',
                'code' => 'FLORENCE',
                'country' => 'Italy',
                'region' => 'Tuscany',
                'headquarters_city' => 'Florence',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Historic archdiocese in Tuscany',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Turin',
                'code' => 'TURIN',
                'country' => 'Italy',
                'region' => 'Piedmont',
                'headquarters_city' => 'Turin',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese in Northern Italy',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Palermo',
                'code' => 'PALERMO',
                'country' => 'Italy',
                'region' => 'Sicily',
                'headquarters_city' => 'Palermo',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese in Sicily',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Bologna',
                'code' => 'BOLOGNA',
                'country' => 'Italy',
                'region' => 'Emilia-Romagna',
                'headquarters_city' => 'Bologna',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Historic archdiocese in Central Italy',
                'website' => null,
                'active' => 1,
            ],

            // ================================================================
            // FRANCE - Catholic Dioceses and Archdioceses
            // ================================================================
            [
                'name' => 'Archdiocese of Paris',
                'code' => 'PARIS',
                'country' => 'France',
                'region' => 'Île-de-France',
                'headquarters_city' => 'Paris',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Metropolitan archdiocese of the capital',
                'website' => 'https://www.paris.catholique.fr',
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Lyon',
                'code' => 'LYON',
                'country' => 'France',
                'region' => 'Auvergne-Rhône-Alpes',
                'headquarters_city' => 'Lyon',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Primatial See of France',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Marseille',
                'code' => 'MARSEILLE',
                'country' => 'France',
                'region' => 'Provence-Alpes-Côte d\'Azur',
                'headquarters_city' => 'Marseille',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese in Southern France',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Toulouse',
                'code' => 'TOULOUSE',
                'country' => 'France',
                'region' => 'Occitanie',
                'headquarters_city' => 'Toulouse',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese in Southwest France',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Reims',
                'code' => 'REIMS',
                'country' => 'France',
                'region' => 'Grand Est',
                'headquarters_city' => 'Reims',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Historic archdiocese, coronation site of French kings',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Bordeaux',
                'code' => 'BORDEAUX',
                'country' => 'France',
                'region' => 'Nouvelle-Aquitaine',
                'headquarters_city' => 'Bordeaux',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese in Southwest France',
                'website' => null,
                'active' => 1,
            ],

            // ================================================================
            // SPAIN - Catholic Dioceses and Archdioceses
            // ================================================================
            [
                'name' => 'Archdiocese of Madrid',
                'code' => 'MADRID',
                'country' => 'Spain',
                'region' => 'Community of Madrid',
                'headquarters_city' => 'Madrid',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Archdiocese of the capital',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Barcelona',
                'code' => 'BARCELONA',
                'country' => 'Spain',
                'region' => 'Catalonia',
                'headquarters_city' => 'Barcelona',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese in Catalonia',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Seville',
                'code' => 'SEVILLE',
                'country' => 'Spain',
                'region' => 'Andalusia',
                'headquarters_city' => 'Seville',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese in Southern Spain',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Valencia',
                'code' => 'VALENCIA',
                'country' => 'Spain',
                'region' => 'Valencian Community',
                'headquarters_city' => 'Valencia',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese on the Mediterranean coast',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Toledo',
                'code' => 'TOLEDO',
                'country' => 'Spain',
                'region' => 'Castilla-La Mancha',
                'headquarters_city' => 'Toledo',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Primatial See of Spain',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Santiago de Compostela',
                'code' => 'SANTIAGO',
                'country' => 'Spain',
                'region' => 'Galicia',
                'headquarters_city' => 'Santiago de Compostela',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Historic pilgrimage site archdiocese',
                'website' => null,
                'active' => 1,
            ],

            // ================================================================
            // GERMANY - Catholic Dioceses and Archdioceses
            // ================================================================
            [
                'name' => 'Archdiocese of Munich and Freising',
                'code' => 'MUNICH',
                'country' => 'Germany',
                'region' => 'Bavaria',
                'headquarters_city' => 'Munich',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese in Bavaria',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Cologne',
                'code' => 'COLOGNE',
                'country' => 'Germany',
                'region' => 'North Rhine-Westphalia',
                'headquarters_city' => 'Cologne',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Largest archdiocese in Germany',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Berlin',
                'code' => 'BERLIN',
                'country' => 'Germany',
                'region' => 'Berlin',
                'headquarters_city' => 'Berlin',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Archdiocese of the capital',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Hamburg',
                'code' => 'HAMBURG',
                'country' => 'Germany',
                'region' => 'Hamburg',
                'headquarters_city' => 'Hamburg',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Archdiocese in Northern Germany',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Freiburg',
                'code' => 'FREIBURG',
                'country' => 'Germany',
                'region' => 'Baden-Württemberg',
                'headquarters_city' => 'Freiburg',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese in Southwest Germany',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Paderborn',
                'code' => 'PADERBORN',
                'country' => 'Germany',
                'region' => 'North Rhine-Westphalia',
                'headquarters_city' => 'Paderborn',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Historic archdiocese in Western Germany',
                'website' => null,
                'active' => 1,
            ],

            // ================================================================
            // NIGERIA - Catholic Dioceses and Archdioceses
            // ================================================================
            [
                'name' => 'Archdiocese of Lagos',
                'code' => 'LAGOS',
                'country' => 'Nigeria',
                'region' => 'Lagos State',
                'headquarters_city' => 'Lagos',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese in West Africa',
                'website' => 'https://www.lagosarchdiocese.org',
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Abuja',
                'code' => 'ABUJA',
                'country' => 'Nigeria',
                'region' => 'Federal Capital Territory',
                'headquarters_city' => 'Abuja',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Archdiocese of the capital',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Onitsha',
                'code' => 'ONITSHA',
                'country' => 'Nigeria',
                'region' => 'Anambra State',
                'headquarters_city' => 'Onitsha',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese in Southeast Nigeria',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Ibadan',
                'code' => 'IBADAN',
                'country' => 'Nigeria',
                'region' => 'Oyo State',
                'headquarters_city' => 'Ibadan',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese in Southwest Nigeria',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Benin City',
                'code' => 'BENIN_CITY',
                'country' => 'Nigeria',
                'region' => 'Edo State',
                'headquarters_city' => 'Benin City',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese in South-South Nigeria',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Kaduna',
                'code' => 'KADUNA',
                'country' => 'Nigeria',
                'region' => 'Kaduna State',
                'headquarters_city' => 'Kaduna',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese in Northern Nigeria',
                'website' => null,
                'active' => 1,
            ],

            // ================================================================
            // MEXICO - Catholic Dioceses and Archdioceses
            // ================================================================
            [
                'name' => 'Archdiocese of Mexico City',
                'code' => 'MEXICO_CITY',
                'country' => 'Mexico',
                'region' => 'Mexico City',
                'headquarters_city' => 'Mexico City',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Oldest diocese in the Americas, Primate of Mexico',
                'website' => 'https://www.arquidiocesismexico.org.mx',
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Guadalajara',
                'code' => 'GUADALAJARA',
                'country' => 'Mexico',
                'region' => 'Jalisco',
                'headquarters_city' => 'Guadalajara',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese in Western Mexico',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Monterrey',
                'code' => 'MONTERREY',
                'country' => 'Mexico',
                'region' => 'Nuevo León',
                'headquarters_city' => 'Monterrey',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese in Northern Mexico',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Puebla',
                'code' => 'PUEBLA',
                'country' => 'Mexico',
                'region' => 'Puebla',
                'headquarters_city' => 'Puebla',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Historic archdiocese in Central Mexico',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Tijuana',
                'code' => 'TIJUANA',
                'country' => 'Mexico',
                'region' => 'Baja California',
                'headquarters_city' => 'Tijuana',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Border archdiocese in Northwest Mexico',
                'website' => null,
                'active' => 1,
            ],

            // ================================================================
            // POLAND - Catholic Dioceses and Archdioceses
            // ================================================================
            [
                'name' => 'Archdiocese of Warsaw',
                'code' => 'WARSAW',
                'country' => 'Poland',
                'region' => 'Mazovia',
                'headquarters_city' => 'Warsaw',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Archdiocese of the capital',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Kraków (Cracow)',
                'code' => 'KRAKOW',
                'country' => 'Poland',
                'region' => 'Lesser Poland',
                'headquarters_city' => 'Kraków',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Historic archdiocese, former see of Pope John Paul II',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Poznań',
                'code' => 'POZNAN',
                'country' => 'Poland',
                'region' => 'Greater Poland',
                'headquarters_city' => 'Poznań',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Oldest archdiocese in Poland',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Wrocław',
                'code' => 'WROCLAW',
                'country' => 'Poland',
                'region' => 'Lower Silesia',
                'headquarters_city' => 'Wrocław',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese in Western Poland',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Gdańsk',
                'code' => 'GDANSK',
                'country' => 'Poland',
                'region' => 'Pomerania',
                'headquarters_city' => 'Gdańsk',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese in Northern Poland',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Łódź',
                'code' => 'LODZ',
                'country' => 'Poland',
                'region' => 'Łódź Voivodeship',
                'headquarters_city' => 'Łódź',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese in Central Poland',
                'website' => null,
                'active' => 1,
            ],

            // ================================================================
            // CANADA - Catholic Dioceses and Archdioceses
            // ================================================================
            [
                'name' => 'Archdiocese of Toronto',
                'code' => 'TORONTO',
                'country' => 'Canada',
                'region' => 'Ontario',
                'headquarters_city' => 'Toronto',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Largest archdiocese in English-speaking Canada',
                'website' => 'https://www.archtoronto.org',
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Montreal',
                'code' => 'MONTREAL',
                'country' => 'Canada',
                'region' => 'Quebec',
                'headquarters_city' => 'Montreal',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese in Quebec',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Quebec',
                'code' => 'QUEBEC',
                'country' => 'Canada',
                'region' => 'Quebec',
                'headquarters_city' => 'Quebec City',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Oldest diocese in Canada, Primate of Canada',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Vancouver',
                'code' => 'VANCOUVER',
                'country' => 'Canada',
                'region' => 'British Columbia',
                'headquarters_city' => 'Vancouver',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese on the West Coast',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Ottawa',
                'code' => 'OTTAWA',
                'country' => 'Canada',
                'region' => 'Ontario',
                'headquarters_city' => 'Ottawa',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Archdiocese of the capital',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Edmonton',
                'code' => 'EDMONTON',
                'country' => 'Canada',
                'region' => 'Alberta',
                'headquarters_city' => 'Edmonton',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese in Western Canada',
                'website' => null,
                'active' => 1,
            ],

            // ================================================================
            // ARGENTINA - Catholic Dioceses and Archdioceses
            // ================================================================
            [
                'name' => 'Archdiocese of Buenos Aires',
                'code' => 'BUENOS_AIRES',
                'country' => 'Argentina',
                'region' => 'Buenos Aires',
                'headquarters_city' => 'Buenos Aires',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Primate archdiocese of Argentina, former see of Pope Francis',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Córdoba',
                'code' => 'CORDOBA_ARG',
                'country' => 'Argentina',
                'region' => 'Córdoba',
                'headquarters_city' => 'Córdoba',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese in Central Argentina',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of La Plata',
                'code' => 'LA_PLATA',
                'country' => 'Argentina',
                'region' => 'Buenos Aires Province',
                'headquarters_city' => 'La Plata',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese in Buenos Aires Province',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Rosario',
                'code' => 'ROSARIO',
                'country' => 'Argentina',
                'region' => 'Santa Fe',
                'headquarters_city' => 'Rosario',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese in Santa Fe Province',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Mendoza',
                'code' => 'MENDOZA',
                'country' => 'Argentina',
                'region' => 'Mendoza',
                'headquarters_city' => 'Mendoza',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese in Western Argentina',
                'website' => null,
                'active' => 1,
            ],

            // ================================================================
            // KENYA - Catholic Dioceses and Archdioceses
            // ================================================================
            [
                'name' => 'Archdiocese of Nairobi',
                'code' => 'NAIROBI',
                'country' => 'Kenya',
                'region' => 'Nairobi County',
                'headquarters_city' => 'Nairobi',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Metropolitan archdiocese of the capital',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Mombasa',
                'code' => 'MOMBASA',
                'country' => 'Kenya',
                'region' => 'Mombasa County',
                'headquarters_city' => 'Mombasa',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese on the coast',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Kisumu',
                'code' => 'KISUMU',
                'country' => 'Kenya',
                'region' => 'Kisumu County',
                'headquarters_city' => 'Kisumu',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese in Western Kenya',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Nyeri',
                'code' => 'NYERI',
                'country' => 'Kenya',
                'region' => 'Nyeri County',
                'headquarters_city' => 'Nyeri',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese in Central Kenya',
                'website' => null,
                'active' => 1,
            ],

            // ================================================================
            // AUSTRALIA - Catholic Dioceses and Archdioceses
            // ================================================================
            [
                'name' => 'Archdiocese of Sydney',
                'code' => 'SYDNEY',
                'country' => 'Australia',
                'region' => 'New South Wales',
                'headquarters_city' => 'Sydney',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Oldest and largest archdiocese in Australia',
                'website' => 'https://www.sydneycatholic.org',
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Melbourne',
                'code' => 'MELBOURNE',
                'country' => 'Australia',
                'region' => 'Victoria',
                'headquarters_city' => 'Melbourne',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese in Victoria',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Brisbane',
                'code' => 'BRISBANE',
                'country' => 'Australia',
                'region' => 'Queensland',
                'headquarters_city' => 'Brisbane',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese in Queensland',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Perth',
                'code' => 'PERTH',
                'country' => 'Australia',
                'region' => 'Western Australia',
                'headquarters_city' => 'Perth',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese in Western Australia',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Adelaide',
                'code' => 'ADELAIDE',
                'country' => 'Australia',
                'region' => 'South Australia',
                'headquarters_city' => 'Adelaide',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major archdiocese in South Australia',
                'website' => null,
                'active' => 1,
            ],

            // ================================================================
            // UNITED KINGDOM - Catholic & Anglican Dioceses
            // ================================================================
            [
                'name' => 'Archdiocese of Westminster',
                'code' => 'WESTMINSTER',
                'country' => 'United Kingdom',
                'region' => 'England',
                'headquarters_city' => 'London',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Metropolitan archdiocese of Catholic Church in England and Wales',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Diocese of London (Anglican)',
                'code' => 'LONDON_ANGLICAN',
                'country' => 'United Kingdom',
                'region' => 'England',
                'headquarters_city' => 'London',
                'denomination_id' => $anglicanId,
                'parent_archdiocese_id' => null,
                'description' => 'Anglican Diocese of London',
                'website' => 'https://www.london.anglican.org',
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Canterbury (Anglican)',
                'code' => 'CANTERBURY',
                'country' => 'United Kingdom',
                'region' => 'England',
                'headquarters_city' => 'Canterbury',
                'denomination_id' => $anglicanId,
                'parent_archdiocese_id' => null,
                'description' => 'Mother church of the worldwide Anglican Communion',
                'website' => 'https://www.canterburydiocese.org',
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Liverpool',
                'code' => 'LIVERPOOL_CATHOLIC',
                'country' => 'United Kingdom',
                'region' => 'England',
                'headquarters_city' => 'Liverpool',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major Catholic archdiocese in Northwest England',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Birmingham',
                'code' => 'BIRMINGHAM_CATHOLIC',
                'country' => 'United Kingdom',
                'region' => 'England',
                'headquarters_city' => 'Birmingham',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major Catholic archdiocese in the Midlands',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of Glasgow',
                'code' => 'GLASGOW',
                'country' => 'United Kingdom',
                'region' => 'Scotland',
                'headquarters_city' => 'Glasgow',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Major Catholic archdiocese in Scotland',
                'website' => null,
                'active' => 1,
            ],
            [
                'name' => 'Archdiocese of St Andrews and Edinburgh',
                'code' => 'EDINBURGH',
                'country' => 'United Kingdom',
                'region' => 'Scotland',
                'headquarters_city' => 'Edinburgh',
                'denomination_id' => $catholicId,
                'parent_archdiocese_id' => null,
                'description' => 'Metropolitan archdiocese of Scotland',
                'website' => null,
                'active' => 1,
            ],

            // ================================================================
            // GENERAL / INDEPENDENT
            // ================================================================
            [
                'name' => 'Independent Church',
                'code' => 'INDEPENDENT',
                'country' => 'Various',
                'region' => null,
                'headquarters_city' => null,
                'denomination_id' => null,
                'parent_archdiocese_id' => null,
                'description' => 'For churches not affiliated with any archdiocese',
                'website' => null,
                'active' => 1,
            ],
        ];

        $now = Carbon::now();

        foreach ($archdioceses as &$archdiocese) {
            $archdiocese['created_at'] = $now;
            $archdiocese['updated_at'] = $now;
        }

        DB::table('archdioceses')->insert($archdioceses);

        $this->command->info('✓ Comprehensive archdioceses dataset seeded successfully!');
        $this->command->info('  Total archdioceses seeded: ' . count($archdioceses));
    }
}
